name: Deploy Flutter Web

on:
  push:
    branches: [ main ] # Change to 'master' if your default branch is named master

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build Web App
        working-directory: ./frontend
        run: |
          flutter create . --platforms web
          flutter pub get
          flutter build web --base-href /${{ github.event.repository.name }}/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/build/web
      - uses: actions/deploy-pages@v4
